[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

# Normal colors
[colors.normal]
black = "#090618"
blue = "#7E9CD8"
cyan = "#6A9589"
green = "#76946A"
magenta = "#957FB8"
red = "#C34043"
white = "#C8C093"
yellow = "#C0A36E"

# Bright colors
[colors.bright]
black = "#727169"
blue = "#7FB4CA"
cyan = "#7AA89F"
green = "#98BB6C"
magenta = "#938AA9"
red = "#E82424"
white = "#DCD7BA"
yellow = "#E6C384"

# Indexed Colors
[[colors.indexed_colors]]
color = "#FFA066"
index = 16

[[colors.indexed_colors]]
color = "#FF5D62"
index = 17

[colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[font.bold]
family = "SourceCodePro"
style = "SemiBold"

[font.bold_italic]
family = "SourceCodePro"
style = "SemiBoldIt"

[font.italic]
family = "SourceCodePro"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Regular"
