#! /usr/bin/env bash

if [[ $1 == "name" ]]; then
	whoami
fi

if [[ $1 == "os" ]]; then
	cat /etc/os-release | grep "^NAME" | awk -F '=' '{print $2}'
fi

if [[ $1 == "pkgs" ]]; then
	nix-store -qR /run/current-system | wc -l
fi

if [[ $1 == "wm" ]]; then
	echo "$XDG_CURRENT_DESKTOP"
fi

if [[ $1 == "icon" ]]; then
	echo "$XDG_CONFIG_HOME/eww/power-menu/assets/avatar.png"
fi
