#! /usr/bin/env bash

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while 

    initial=$(jq -n '[range(1;11) | {id:., visible:false, busy:false}]')

    busy=$(hyprctl workspaces -j | jq '.[].id')

    visible=$(hyprctl activeworkspace -j | jq '.id')

    current=$(echo "$initial" | jq --arg busy "$busy"  --arg visible "$visible" '
        ($busy | split("\n") | map(tonumber)) as $busy | 
        ($visible | tonumber) as $visible |
        .[$visible - 1].visible = true |
        .[$busy | .[] - 1].busy = true
    ')
    echo $current

    read -r event; 
do true; done
